/** Auto-generated from linuxdoom-1.10/info.c — do not edit by hand. */

export interface GeneratedThingRow {
  type: number;
  spriteName: string;
  frame: string;
  rotation: number;
  radius: number;
  height: number;
  flags: number;
  health: number;
  painChance: number;
  countsTowardKill: boolean;
  countsTowardItem: boolean;
  category: 'monster' | 'weapon' | 'ammo' | 'health' | 'powerup' | 'key' | 'decoration' | 'player';
  mobjName: string;
}

export const GENERATED_THING_INFO_ROWS: GeneratedThingRow[] = [
  {
    type: 5,
    spriteName: 'BKEY',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 33554433,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'key',
    mobjName: 'MISC4',
  },
  {
    type: 6,
    spriteName: 'YKEY',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 33554433,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'key',
    mobjName: 'MISC6',
  },
  {
    type: 7,
    spriteName: 'SPID',
    frame: 'A',
    rotation: 0,
    radius: 8388608,
    height: 6553600,
    flags: 4194310,
    health: 3000,
    painChance: 40,
    countsTowardKill: true,
    countsTowardItem: false,
    category: 'monster',
    mobjName: 'SPIDER',
  },
  {
    type: 8,
    spriteName: 'BPAK',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'ammo',
    mobjName: 'MISC24',
  },
  {
    type: 9,
    spriteName: 'SPOS',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 3670016,
    flags: 4194310,
    health: 30,
    painChance: 170,
    countsTowardKill: true,
    countsTowardItem: false,
    category: 'monster',
    mobjName: 'SHOTGUY',
  },
  {
    type: 10,
    spriteName: 'PLAY',
    frame: 'W',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 0,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC68',
  },
  {
    type: 12,
    spriteName: 'PLAY',
    frame: 'W',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 0,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC69',
  },
  {
    type: 13,
    spriteName: 'RKEY',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 33554433,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'key',
    mobjName: 'MISC5',
  },
  {
    type: 14,
    spriteName: 'TROO',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 24,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'TELEPORTMAN',
  },
  {
    type: 15,
    spriteName: 'PLAY',
    frame: 'N',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 0,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC62',
  },
  {
    type: 16,
    spriteName: 'CYBR',
    frame: 'A',
    rotation: 0,
    radius: 2621440,
    height: 7208960,
    flags: 4194310,
    health: 4000,
    painChance: 20,
    countsTowardKill: true,
    countsTowardItem: false,
    category: 'monster',
    mobjName: 'CYBORG',
  },
  {
    type: 17,
    spriteName: 'CELP',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'ammo',
    mobjName: 'MISC21',
  },
  {
    type: 18,
    spriteName: 'POSS',
    frame: 'L',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 0,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC63',
  },
  {
    type: 19,
    spriteName: 'SPOS',
    frame: 'L',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 0,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC67',
  },
  {
    type: 20,
    spriteName: 'TROO',
    frame: 'M',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 0,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC66',
  },
  {
    type: 21,
    spriteName: 'SARG',
    frame: 'N',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 0,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC64',
  },
  {
    type: 22,
    spriteName: 'HEAD',
    frame: 'L',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 0,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC61',
  },
  {
    type: 23,
    spriteName: 'SKUL',
    frame: 'K',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 0,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC65',
  },
  {
    type: 24,
    spriteName: 'POL5',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 0,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC71',
  },
  {
    type: 25,
    spriteName: 'POL1',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC74',
  },
  {
    type: 26,
    spriteName: 'POL6',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC75',
  },
  {
    type: 27,
    spriteName: 'POL4',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC72',
  },
  {
    type: 28,
    spriteName: 'POL2',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC70',
  },
  {
    type: 29,
    spriteName: 'POL3',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC73',
  },
  {
    type: 30,
    spriteName: 'COL1',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC32',
  },
  {
    type: 31,
    spriteName: 'COL2',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC33',
  },
  {
    type: 32,
    spriteName: 'COL3',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC34',
  },
  {
    type: 33,
    spriteName: 'COL4',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC35',
  },
  {
    type: 34,
    spriteName: 'CAND',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 0,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC49',
  },
  {
    type: 35,
    spriteName: 'CBRA',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC50',
  },
  {
    type: 36,
    spriteName: 'COL5',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC37',
  },
  {
    type: 37,
    spriteName: 'COL6',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC36',
  },
  {
    type: 38,
    spriteName: 'RSKU',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 33554433,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'key',
    mobjName: 'MISC8',
  },
  {
    type: 39,
    spriteName: 'YSKU',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 33554433,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'key',
    mobjName: 'MISC7',
  },
  {
    type: 40,
    spriteName: 'BSKU',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 33554433,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'key',
    mobjName: 'MISC9',
  },
  {
    type: 41,
    spriteName: 'CEYE',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC38',
  },
  {
    type: 42,
    spriteName: 'FSKU',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC39',
  },
  {
    type: 43,
    spriteName: 'TRE1',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC40',
  },
  {
    type: 44,
    spriteName: 'TBLU',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC41',
  },
  {
    type: 45,
    spriteName: 'TGRN',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC42',
  },
  {
    type: 46,
    spriteName: 'TRED',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC43',
  },
  {
    type: 47,
    spriteName: 'SMIT',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC47',
  },
  {
    type: 48,
    spriteName: 'ELEC',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC48',
  },
  {
    type: 49,
    spriteName: 'GOR1',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 4456448,
    flags: 770,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC51',
  },
  {
    type: 50,
    spriteName: 'GOR2',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 5505024,
    flags: 770,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC52',
  },
  {
    type: 51,
    spriteName: 'GOR3',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 5505024,
    flags: 770,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC53',
  },
  {
    type: 52,
    spriteName: 'GOR4',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 4456448,
    flags: 770,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC54',
  },
  {
    type: 53,
    spriteName: 'GOR5',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 3407872,
    flags: 770,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC55',
  },
  {
    type: 54,
    spriteName: 'TRE2',
    frame: 'A',
    rotation: 0,
    radius: 2097152,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC76',
  },
  {
    type: 55,
    spriteName: 'SMBT',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC44',
  },
  {
    type: 56,
    spriteName: 'SMGT',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC45',
  },
  {
    type: 57,
    spriteName: 'SMRT',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC46',
  },
  {
    type: 58,
    spriteName: 'SARG',
    frame: 'A',
    rotation: 0,
    radius: 1966080,
    height: 3670016,
    flags: 4456454,
    health: 150,
    painChance: 180,
    countsTowardKill: true,
    countsTowardItem: false,
    category: 'monster',
    mobjName: 'SHADOWS',
  },
  {
    type: 59,
    spriteName: 'GOR2',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 5505024,
    flags: 768,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC56',
  },
  {
    type: 60,
    spriteName: 'GOR4',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 4456448,
    flags: 768,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC57',
  },
  {
    type: 61,
    spriteName: 'GOR3',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 3407872,
    flags: 768,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC58',
  },
  {
    type: 62,
    spriteName: 'GOR5',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 3407872,
    flags: 768,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC59',
  },
  {
    type: 63,
    spriteName: 'GOR1',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 4456448,
    flags: 768,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC60',
  },
  {
    type: 64,
    spriteName: 'VILE',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 3670016,
    flags: 4194310,
    health: 700,
    painChance: 10,
    countsTowardKill: true,
    countsTowardItem: false,
    category: 'monster',
    mobjName: 'VILE',
  },
  {
    type: 65,
    spriteName: 'CPOS',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 3670016,
    flags: 4194310,
    health: 70,
    painChance: 170,
    countsTowardKill: true,
    countsTowardItem: false,
    category: 'monster',
    mobjName: 'CHAINGUY',
  },
  {
    type: 66,
    spriteName: 'SKEL',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 3670016,
    flags: 4194310,
    health: 300,
    painChance: 100,
    countsTowardKill: true,
    countsTowardItem: false,
    category: 'monster',
    mobjName: 'UNDEAD',
  },
  {
    type: 67,
    spriteName: 'FATT',
    frame: 'A',
    rotation: 0,
    radius: 3145728,
    height: 4194304,
    flags: 4194310,
    health: 600,
    painChance: 80,
    countsTowardKill: true,
    countsTowardItem: false,
    category: 'monster',
    mobjName: 'FATSO',
  },
  {
    type: 68,
    spriteName: 'BSPI',
    frame: 'A',
    rotation: 0,
    radius: 4194304,
    height: 4194304,
    flags: 4194310,
    health: 500,
    painChance: 128,
    countsTowardKill: true,
    countsTowardItem: false,
    category: 'monster',
    mobjName: 'BABY',
  },
  {
    type: 69,
    spriteName: 'BOS2',
    frame: 'A',
    rotation: 0,
    radius: 1572864,
    height: 4194304,
    flags: 4194310,
    health: 500,
    painChance: 50,
    countsTowardKill: true,
    countsTowardItem: false,
    category: 'monster',
    mobjName: 'KNIGHT',
  },
  {
    type: 70,
    spriteName: 'FCAN',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC77',
  },
  {
    type: 71,
    spriteName: 'PAIN',
    frame: 'A',
    rotation: 0,
    radius: 2031616,
    height: 3670016,
    flags: 4211206,
    health: 400,
    painChance: 128,
    countsTowardKill: true,
    countsTowardItem: false,
    category: 'monster',
    mobjName: 'PAIN',
  },
  {
    type: 72,
    spriteName: 'KEEN',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 4718592,
    flags: 4195078,
    health: 100,
    painChance: 256,
    countsTowardKill: true,
    countsTowardItem: false,
    category: 'monster',
    mobjName: 'KEEN',
  },
  {
    type: 73,
    spriteName: 'HDB1',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 5767168,
    flags: 770,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC78',
  },
  {
    type: 74,
    spriteName: 'HDB2',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 5767168,
    flags: 770,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC79',
  },
  {
    type: 75,
    spriteName: 'HDB3',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 4194304,
    flags: 770,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC80',
  },
  {
    type: 76,
    spriteName: 'HDB4',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 4194304,
    flags: 770,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC81',
  },
  {
    type: 77,
    spriteName: 'HDB5',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 4194304,
    flags: 770,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC82',
  },
  {
    type: 78,
    spriteName: 'HDB6',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 4194304,
    flags: 770,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC83',
  },
  {
    type: 79,
    spriteName: 'POB1',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 16,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC84',
  },
  {
    type: 80,
    spriteName: 'POB2',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 16,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC85',
  },
  {
    type: 81,
    spriteName: 'BRS1',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 16,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC86',
  },
  {
    type: 82,
    spriteName: 'SGN2',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'weapon',
    mobjName: 'SUPERSHOTGUN',
  },
  {
    type: 83,
    spriteName: 'MEGA',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 8388609,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: true,
    category: 'powerup',
    mobjName: 'MEGA',
  },
  {
    type: 84,
    spriteName: 'SSWV',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 3670016,
    flags: 4194310,
    health: 50,
    painChance: 170,
    countsTowardKill: true,
    countsTowardItem: false,
    category: 'monster',
    mobjName: 'WOLFSS',
  },
  {
    type: 85,
    spriteName: 'TLMP',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC29',
  },
  {
    type: 86,
    spriteName: 'TLP2',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC30',
  },
  {
    type: 87,
    spriteName: 'TROO',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 2097152,
    flags: 24,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'BOSSTARGET',
  },
  {
    type: 88,
    spriteName: 'BBRN',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 6,
    health: 250,
    painChance: 255,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'BOSSBRAIN',
  },
  {
    type: 89,
    spriteName: 'SSWV',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 2097152,
    flags: 24,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'BOSSSPIT',
  },
  {
    type: 2001,
    spriteName: 'SHOT',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'weapon',
    mobjName: 'SHOTGUN',
  },
  {
    type: 2002,
    spriteName: 'MGUN',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'weapon',
    mobjName: 'CHAINGUN',
  },
  {
    type: 2003,
    spriteName: 'LAUN',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'weapon',
    mobjName: 'MISC27',
  },
  {
    type: 2004,
    spriteName: 'PLAS',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'weapon',
    mobjName: 'MISC28',
  },
  {
    type: 2005,
    spriteName: 'CSAW',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'weapon',
    mobjName: 'MISC26',
  },
  {
    type: 2006,
    spriteName: 'BFUG',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'weapon',
    mobjName: 'MISC25',
  },
  {
    type: 2007,
    spriteName: 'CLIP',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'ammo',
    mobjName: 'CLIP',
  },
  {
    type: 2008,
    spriteName: 'SHEL',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'ammo',
    mobjName: 'MISC22',
  },
  {
    type: 2010,
    spriteName: 'ROCK',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'ammo',
    mobjName: 'MISC18',
  },
  {
    type: 2011,
    spriteName: 'STIM',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'health',
    mobjName: 'MISC10',
  },
  {
    type: 2012,
    spriteName: 'MEDI',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'health',
    mobjName: 'MISC11',
  },
  {
    type: 2013,
    spriteName: 'SOUL',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 8388609,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: true,
    category: 'powerup',
    mobjName: 'MISC12',
  },
  {
    type: 2014,
    spriteName: 'BON1',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 8388609,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: true,
    category: 'health',
    mobjName: 'MISC2',
  },
  {
    type: 2015,
    spriteName: 'BON2',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 8388609,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: true,
    category: 'health',
    mobjName: 'MISC3',
  },
  {
    type: 2018,
    spriteName: 'ARM1',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'health',
    mobjName: 'MISC0',
  },
  {
    type: 2019,
    spriteName: 'ARM2',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'health',
    mobjName: 'MISC1',
  },
  {
    type: 2022,
    spriteName: 'PINV',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 8388609,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: true,
    category: 'powerup',
    mobjName: 'INV',
  },
  {
    type: 2023,
    spriteName: 'PSTR',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 8388609,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: true,
    category: 'powerup',
    mobjName: 'MISC13',
  },
  {
    type: 2024,
    spriteName: 'PINS',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 8388609,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: true,
    category: 'powerup',
    mobjName: 'INS',
  },
  {
    type: 2025,
    spriteName: 'SUIT',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'powerup',
    mobjName: 'MISC14',
  },
  {
    type: 2026,
    spriteName: 'PMAP',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 8388609,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: true,
    category: 'powerup',
    mobjName: 'MISC15',
  },
  {
    type: 2028,
    spriteName: 'COLU',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 1048576,
    flags: 2,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'MISC31',
  },
  {
    type: 2035,
    spriteName: 'BAR1',
    frame: 'A',
    rotation: 0,
    radius: 655360,
    height: 2752512,
    flags: 524294,
    health: 20,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'BARREL',
  },
  {
    type: 2045,
    spriteName: 'PVIS',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 8388609,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: true,
    category: 'powerup',
    mobjName: 'MISC16',
  },
  {
    type: 2046,
    spriteName: 'BROK',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'ammo',
    mobjName: 'MISC19',
  },
  {
    type: 2047,
    spriteName: 'CELL',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'ammo',
    mobjName: 'MISC20',
  },
  {
    type: 2048,
    spriteName: 'AMMO',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'ammo',
    mobjName: 'MISC17',
  },
  {
    type: 2049,
    spriteName: 'SBOX',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 1048576,
    flags: 1,
    health: 1000,
    painChance: 0,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'ammo',
    mobjName: 'MISC23',
  },
  {
    type: 3001,
    spriteName: 'TROO',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 3670016,
    flags: 4194310,
    health: 60,
    painChance: 200,
    countsTowardKill: true,
    countsTowardItem: false,
    category: 'monster',
    mobjName: 'TROOP',
  },
  {
    type: 3002,
    spriteName: 'SARG',
    frame: 'A',
    rotation: 0,
    radius: 1966080,
    height: 3670016,
    flags: 4194310,
    health: 150,
    painChance: 180,
    countsTowardKill: true,
    countsTowardItem: false,
    category: 'monster',
    mobjName: 'SERGEANT',
  },
  {
    type: 3003,
    spriteName: 'BOSS',
    frame: 'A',
    rotation: 0,
    radius: 1572864,
    height: 4194304,
    flags: 4194310,
    health: 1000,
    painChance: 50,
    countsTowardKill: true,
    countsTowardItem: false,
    category: 'monster',
    mobjName: 'BRUISER',
  },
  {
    type: 3004,
    spriteName: 'POSS',
    frame: 'A',
    rotation: 0,
    radius: 1310720,
    height: 3670016,
    flags: 4194310,
    health: 20,
    painChance: 200,
    countsTowardKill: true,
    countsTowardItem: false,
    category: 'monster',
    mobjName: 'POSSESSED',
  },
  {
    type: 3005,
    spriteName: 'HEAD',
    frame: 'A',
    rotation: 0,
    radius: 2031616,
    height: 3670016,
    flags: 4211206,
    health: 400,
    painChance: 128,
    countsTowardKill: true,
    countsTowardItem: false,
    category: 'monster',
    mobjName: 'HEAD',
  },
  {
    type: 3006,
    spriteName: 'SKUL',
    frame: 'A',
    rotation: 0,
    radius: 1048576,
    height: 3670016,
    flags: 16902,
    health: 100,
    painChance: 256,
    countsTowardKill: false,
    countsTowardItem: false,
    category: 'decoration',
    mobjName: 'SKULL',
  },
];
